version: '3'
services: 
    app:
        container_name: blockchain-api-basics
        restart: always
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - '3000:3000'
